### ISSUE TITLE
Google Summer of Code 2018 projects

### ISSUE THREAD

**Issue by smit1678** [hotosm/tech#101]
Yesterday we published an initial list of potential projects for Google Summer of Code 2018. We're working under the umbrella submission from the [DIAL Open Source Center](http://docs.osc.dial.community/en/latest/soc.html). Purpose of this thread is to further the discussion around the project listing. The initial list was to meet deadlines and publish ideas based on conversations we've had over the last few months and existing ideas floating around. Let's hone in on projects. 

As a reminder, GSoC projects are focused on writing code and contributing to open source projects. So I've purposely proposed project ideas that are contributing to existing tools and are less about creating new stand-alone tools. We can certainly consider new ideas but given the short time frame of GSoC it may be easier for onboarding a student by helping them dive in and contribute to an existing tool. Also we should not be pointing to a list of bugs in a repo and calling that a project.

This is an open process and if you have an idea or want to help be a mentor please raise a hand✋! 

### Questions for us to think about: 

* I've included some potential project ideas around MapCampaigner, OAM, Tasking Manager, and the new Visualize Change tool. **What are some other ideas around the Export Tool or other tools within the HOT ecosystem?** 
  - @xivk perhaps something related to OSMSharp? 
* **Who would like to be a mentor?** We'll need to identify mentors. I've filled in myself and few others as placeholders but we'll want to lock in a mentor who can work with the student over the summer. 
* Tasking Manager is a great place for scoping out ideas. **What are other areas we could push on within the TM?** Consider a start to a rewrite in React that completely rethinks the workflow? Develop components related to data quality, campaign management, stats API? 

### Initial list of ideas

Posted here: https://github.com/hotosm/tech/blob/master/project-ideas/google-soc/soc2018.md

- Team management module for MapCampaigner  
  - **Project Description:** MapCampaigner is a field data collection organizing application. Organizers can define an area, define the features to collect, and recruit contributors. A missing component is an improved team management capabilities. This project would look to build out additional admin components for managing and engaging a team of contributors.  

- OpenAerialMap admin user account management  
  - **Project Description:** OpenAerialMap added user accounts in the fall of 2017. One component that was not developed was admin functionalities - admin roles to edit user's profiles and manage a user's imagery. This project would focus on building out the necessary components to add this to the API and frontend.  

- Visualize Change speed and frequency improvements  
  - **Project Description:** Visualize Change is a time-based visualization rendering application that allows any user to define an area of interest and create a web-based visualization along with a mp4 video file for offline viewing. This project would focus on speed improvements to the processing and rendering, and working on the vector tile generation process to improve frequency of OSM data being generated.  

- Machine learning module for Tasking Manager  
  - **Project Description:** The Tasking Manager is HOT's primary application for coordinating and helping expose volunteers to map areas of the world in OpenStreetMap. Over the past year, we've been exploring how to integrate machine learning outputs into a Tasking Manager workflow. This project would focus on building the components to integrate a machine learning output into the Tasking Manager.

**Comment by ethan-nelson** [comment]
For the TM, have we considered a JOSM plugin to interact with the API?

I'm happy to help with mentoring as well. But not with regular Java.

**Comment by yunjuc** [comment]
Hi, I plan to apply for outreachy internship program and am looking for ways to get involved with the community. I submitted a request to join the slack channel last week but haven't had any response. Where does the team discussion usually take place, GitHub? Thanks.

**Comment by bgirardot** [comment]
hi @yunjuc You should have an invite to the HOT slack team. One was sent yesterday and I just resent it a few minutes ago. double check and check your spam folder. It is possible your email address is wrong. if you still do not have the slack team invite, just make another request via the google form and make sure your email address is correct.

**Comment by yunjuc** [comment]
I saw the invite now. Thanks!

**Comment by smit1678** [comment]
@ethan-nelson I added a short write up for the JOSM plugin to the project list. https://github.com/hotosm/tech/pull/107

I also added some OMK Android work to the list based on a discussion with @danbjoseph.
