### ISSUE TITLE
HOT enhancement requests for Esri World imagery MORE than welcome

### ISSUE THREAD

**Issue by jgravois** [hotosm/tech#118]
Hey y'all 👋! 

it was brought to my attention that Esri World Imagery was used in [~1/3](https://www.hotosm.org/updates/open-imagery-for-humanitarian-mapping/) of HOT projects in 2018. that is awesome!

because of htis, i decided to drop a line here and mention that there are _definitely_ developers (and aspiring developers) at Esri that would be interested in adding capabilities/metadata if y'all have any specific asks.

ref:

https://github.com/openstreetmap/iD/pull/5116
https://github.com/openstreetmap/iD/pull/4335

one idea of mine:
- [ ] some kind of port of [World Imagery (Wayback)](https://www.esri.com/arcgis-blog/products/arcgis-living-atlas/imagery/wayback-81-flavors-of-world-imagery/)

we also already have an [iD PR](https://github.com/openstreetmap/iD/pull/4633) languishing that adds the ability to selectively import and QA authoritative spatial data served from Esri web services. if there is potential that this work could be beneficial in a humanitarian context, all the better.

disclaimer: i signed up quite awhile back to get myself invited to tech working group meetings but i've never gotten off my butt to actually dial into one. if _that_ would be the more appropriate venue to talk through details, just say the word.

cc @quincylvania @slibby

**Comment by smit1678** [comment]
@jgravois 👋 awesome, thanks for the issue here. Yes, I will drop in some ideas here, I think that's a great idea. More shortly but they revolve around some improved workflows into the Tasking Manager and then also some potential offline use with OpenMapKit. 

> some kind of port of World Imagery (Wayback)

Sounds interesting and curious to know more about the idea

**Comment by jgravois** [comment]
awesome @smit1678!

> some kind of port of World Imagery (Wayback)
>> curious to know more about the idea

Besides the blog post i linked to previously, the app below is probably the best way to get familiar with Esri's Wayback Imagery service.

* https://livingatlas.arcgis.com/wayback/

if you think having access to historic imagery (back to 2014) in iD to compare/contrast with whatever is fresh could be useful, just say the word.

**Comment by bgirardot** [comment]
Hi @jgravois 

Thank you very much for your offer.

The two most important things to me as someone who creates projects are, native or effective zoom level, date of the imagery at max zoom level (this often changes in DG imagery layers between z17 and z18), and what area the imagery covers.

At the moment, most Esri imagery seems to go up to about z17. If there was anyway to get native or good effective z18 that would help mappers a lot. I might have those numbers off by one, but Esri World imagery is just one zoom level short of what we usually work with from DG and a bit more difficult for mappers to map from as a result.

As to the date of the imagery, there is a website we use to determine the date:

https://www.arcgis.com/home/webmap/viewer.html?webmap=c03a526d94704bfb839445e80de95495

A minor improvement would be to have the capture date available in the meta data of the imagery tiles themselves. Then we could get an idea right in our native tool (JOSM).

However, an other big improvement would be to allow the download of the imagery footprint so we could build projects around the Esri imagery exactly. Often time 2017 imagery will border something much older like 2012 so only working in the area of the 2017 is important.

See this example, the blue outline would be what we want to download:
![2018-12-27_07h42_32](https://user-images.githubusercontent.com/265831/50480681-721be880-09ab-11e9-8cfa-f65c08caebd9.png)

Thank you and thank Esri very much, Esri Worldwide imagery, is often the newest available and works well for us generaly.

**Comment by jgravois** [comment]
### metadata

> As to the date of the imagery, there is a website we use to determine the date:

> A minor improvement would be to have the capture date available in the meta data of the imagery tiles themselves. Then we could get an idea right in our native tool (JOSM).

i actually [PR](https://github.com/openstreetmap/iD/pull/4335)ed this feature in [iD](https://www.openstreetmap.org/edit#map=14/32.7380/-117.0997) last year. it is activated via <kbd>&#8984; Cmd/Ctrl</kbd> + <kbd>&#8679; Shift</kbd> + <kbd>B</kbd>

![screenshot 2018-12-27 10 32 50](https://user-images.githubusercontent.com/3011734/50490604-c5e5fc00-09c2-11e9-83a0-fc3395ca9afe.png)

the information isn't encoded into the actual tiles, but it _is_ accessible via spatial web queries so i'd be happy to act as a resource if you can find someone interested in porting the code into JOSM.

> another big improvement would be to allow the download of the imagery footprint so we could build projects around the Esri imagery exactly.

you could certainly fetch these features as GeoJSON via spatial web queries and display the information in JOSM. would it be helpful for me to write up a quick prototype in Leaflet to outline the flow?

### higher resolution imagery

Esri's catalog is a composite of commercial sources and photography contributed to our [Community Maps Program](https://www.esri.com/arcgis-blog/products/arcgis-online/mapping/whats-new-in-community-maps-august-2018/). we're _always_ pursuing the higher quality and more recent content but in the remote areas where you guys and gals work its not _super_ likely you'll start to see substantially better stuff getting served up.

**Comment by jgravois** [comment]
closing, but always happy to keep the discussion alive.
