### ISSUE TITLE
Missing Maps Leaderboard Related

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tech#123]
Scrubbing

**Comment by ramyaragupathy** [comment]
**11-Nov-2019**
* Ramya supported Yogesh with local backend setup

**Comment by eternaltyro** [comment]
**12-Nov-2019**

### Tasks at hand

- Move Missing Maps resources to new (sponsorship) subscription
- Improve performance of Missing Maps PostgreSQL database

### Switching Subscription

This one appears to be easy to do. We just have to switch the subscription for the existing Resource Group and that should do it. It must be a button click and a few input boxes away.

However, for us to be able to run tests, we need a sandbox / staging Resource Group (also attached to the sponsorship subscription). This is being discussed.

### Improving DB performance

- We hope to improve performance by scaling the DB instance from general purpose to a memory optimized one:

Each core for general purpose instance has 5G of RAM. For Memory Optimized instances, each core has 10GB of RAM. This will help more data to be computed in memory and most of the data to reside in memory for `SELECT` operations. 

- Additionally, there are approaches to improve performance via software. We are considering the following:

1. Creating better indexes (at the cost of disk space) to speed up materialized view refreshes
2. Replace Materialized views with a Trigger's based approach
3. Using VACUUM to clear up dead tuples and ease up server resources.
4. Optimize Queries to reuse intermediary results in the same query.
5. Using later versions of PostgreSQL to take advantage of features like generated columns. 

### Creating better indexes

By running an `EXPLAIN ANALYZE SELECT ...` query, we found that the indexing may be inadequate. The resulting query plans showed that only primary key indexes were used. We can remediate this by creating carefully thought out indexes tailored for the SELECT queries used in the materialized views:

<details>
  <summary>Explain Analyze</summary>
 
 ```
    mm=> EXPLAIN ANALYZE SELECT h.hashtag, count(c.id) AS changesets, count(DISTINCT c.user_id) AS users, sum(c.road_km_added) AS road_km_added, sum(c.road_km_modified) AS road_km_modified, sum(c.waterway_km_added) AS waterway_km_added, sum(c.waterway_km_modified) AS waterway_km_modified, sum(c.roads_added) AS roads_added, sum(c.roads_modified) AS roads_modified, sum(c.waterways_added) AS waterways_added, sum(c.waterways_modified) AS waterways_modified, sum(c.buildings_added) AS buildings_added, sum(c.buildings_modified) AS buildings_modified, sum(c.pois_added) AS pois_added, sum(c.pois_modified) AS pois_modified, sum( CASE WHEN "position"(lower(c.editor), 'josm'::text) > 0 THEN 1 ELSE 0 END) AS josm_edits, max(COALESCE(c.closed_at, c.created_at)) AS updated_at FROM raw_changesets_hashtags ch JOIN raw_changesets c ON c.id = ch.changeset_id JOIN raw_hashtags h ON h.id = ch.hashtag_id GROUP BY h.hashtag;

                                                                                                  QUERY PLAN

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------
 GroupAggregate  (cost=11177710.64..12551735.97 rows=71195 width=139) (actual time=1920040.879..2023439.593 rows=67120 loops=1)
   Group Key: h.hashtag
   ->  Sort  (cost=11177710.64..11243106.52 rows=26158350 width=117) (actual time=1920040.669..1967907.197 rows=25118520 loops=1)
         Sort Key: h.hashtag
         Sort Method: external merge  Disk: 3487352kB
         ->  Hash Join  (cost=46032.84..5127039.20 rows=26158350 width=117) (actual time=48584.799..1606168.490 rows=25118520 loops=1)
               Hash Cond: (ch.hashtag_id = h.id)
               ->  Merge Join  (cost=43649.95..3896091.00 rows=26158350 width=110) (actual time=48433.985..1574344.313 rows=25118520 loops=1)
                     Merge Cond: (ch.changeset_id = c.id)
                     ->  Index Only Scan using raw_changesets_hashtags_pkey on raw_changesets_hashtags ch  (cost=0.44..599011.15 rows=26158350 width=8) (actual time=0.345..15312
1.609 rows=25343390 loops=1)
                           Heap Fetches: 25344037
                     ->  Index Scan using raw_changesets_pkey on raw_changesets c  (cost=0.56..3371147.68 rows=66561872 width=106) (actual time=0.017..1395847.301 rows=88753202
loops=1)
               ->  Hash  (cost=1144.95..1144.95 rows=71195 width=15) (actual time=50.526..50.526 rows=69360 loops=1)
                     Buckets: 131072  Batches: 2  Memory Usage: 2694kB
                     ->  Seq Scan on raw_hashtags h  (cost=0.00..1144.95 rows=71195 width=15) (actual time=0.019..11.508 rows=69360 loops=1)
 Planning time: 23.806 ms
 Execution time: 2024094.024 ms
(17 rows)
```
</details>

Indexes take up disk space, but we have 1TB of disk space to work with.

### Replace Materialized views with a Triggers

Not sure what this would look like.

### Optimizing performance using VACUUM

From PostgreSQL doc: https://www.postgresql.org/docs/9.1/sql-vacuum.html

> VACUUM reclaims storage occupied by dead tuples. In normal PostgreSQL operation, tuples that are deleted or obsoleted by an update are not physically removed from their table; they remain present until a VACUUM is done. Therefore it's necessary to do VACUUM periodically, especially on frequently-updated tables.

>  We recommend that active production databases be vacuumed frequently (at least nightly), in order to remove dead rows. After adding or deleting a large number of rows, it might be a good idea to issue a VACUUM ANALYZE command for the affected table. This will update the system catalogs with the results of all recent changes, and allow the PostgreSQL query planner to make better choices in planning queries.

### Optimize Queries 

Some queries seem like they can be optimized to use intermediary results. I didn't even know how to Google what I was thinking but I found this: https://dba.stackexchange.com/questions/9043/postgresql-reuse-of-complex-intermediate-result-in-same-query

Basically, for `SELECT`s, we do: 
```
FROM ( SELECT raw_changesets_hashtags.hashtag_id,
            raw_changesets.user_id,
            count(raw_changesets.id) AS changesets,
            sum(raw_changesets.buildings_added + raw_changesets.buildings_modified + raw_changesets.roads_added + raw_changesets.roads_modified + raw_changesets.waterways_added + raw_changesets.waterways_modified + raw_changesets.pois_added + raw_changesets.pois_modified) AS edits,
            sum(raw_changesets.buildings_added + raw_changesets.buildings_modified) AS buildings,
            sum(raw_changesets.roads_added + raw_changesets.roads_modified) AS roads,
            sum(raw_changesets.road_km_added + raw_changesets.road_km_modified) AS road_km
```

For those multiple `sum` expressions, we read the table over and over. I feel that this can be simplified and made performant by using Common Table Expressions (CTE) to store and reuse intermediate results like values for `(raw_changesets.buildings_added)` https://www.postgresql.org/docs/8.4/queries-with.html

### Using later versions of PostgreSQL

PostgreSQL 11 has support for GENERATED columns, whose values are computed on the fly. This could potentially be used in addition to overall performance enhancements to the DB engine.

**Comment by eternaltyro** [comment]
Azure PostgreSQL optimizations guide: https://docs.microsoft.com/en-us/azure/postgresql/howto-optimize-autovacuum

Also, I enabled query analysis and data collection no the mm database.

**Comment by ramyaragupathy** [comment]
**14-Nov-2019**

* @eternaltyro identifying queries run through API and analysing if including more indexes would help the read operations
* @ramyaragupathy checking upon setting up triggers instead of views
* @dakotabenjamin @eternaltyro has set up a staging instance on azure server. 

_No updates for 13-Nov-2019 since most of our day time we were involved in dealing with TM outage_

**Comment by ramyaragupathy** [comment]
Our main bottleneck in the process so far has been materialised view refresh. 

For our Leaderboard API queries, hashtag stats or user stats, we need to do the following on our DB tables to get results:

* Union several tables together
* Filter out some rows and
* Sort the unioned set different ways

Each time we want to run this query against the table - it will be time-consuming and exhaustive. So we create the query beforehand and store the results in a `view`  setup from which our backend picks the data by specific filters. When the API queries a `view` we're applying additional projections and filters to an existing query (which has the results stored in our view).

**What is a Materialized View?**
`Materialized views` are disc-stored views that can be refreshed. Like views, they are defined by a database query. Unlike views, their underlying query is not executed every time you access them. Every time you query a `view`, it reproduces itself. Therefore, the view data is never old. However you have to manage the data refresh for materialized views. So it comes down to a data freshness vs. performance tradeoff

You **can’t insert/update data into a materialized view** as you can with a table. To update the contents of a materialized view, you can execute a query to refresh it. This will re-execute the query used to create it.

By default, executing a refresh query will lock the materialized view so it can’t be accessed while refreshing. This can be a problem if your application can’t tolerate downtime while the refresh is happening.

Recent versions of PostgreSQL  allows refresh view in a way that enables queries/read operations during the refresh - using the `concurrent` flag and we employ this technique in our refresh too. This refresh option on our DB in an ideal setup should take 45 minutes in total for the entire process. But currently, refresh is exceeding beyond the time limits and sometimes takes about a day or fails in between resulting in stale data.

**Optimise materialised view operations**
To better optimize materialized view queries, 
* we can add indexes to the materialized view columns similar database table.
* optimise indexes on tables that are used to generate these views
* Identify and remove dead rows - Whenever rows in a PostgreSQL table are updated or deleted, dead rows are left behind. `[VACUUM](https://www.postgresql.org/docs/9.1/sql-vacuum.html)` command gets rid of them so that space can be reused. If a table doesn’t get vacuumed, it will get bloated, which wastes disk space and slows down sequential table scans, affecting the result set query for views.

@eternaltyro is working on indexes and cleaning up the data store using `VACCUM` operation

**Other approached to aggregate data:**

Other option we can look at is:

1.  triggers to do the view refresh - as and when update or insert happens on relevant tables, trigger materialised view refresh form our codebase. 

However, each refresh - whether it comes from a trigger or a manual process, re-runs the query used to create the materialised view and replaces all of the data with a current snapshot.
So triggers also does an entire refresh of the views and not update individual rows within the view.

2. using triggers to update a table WITH A FILTER (corresponding to whatever fired the trigger) will perform a partial update of the aggregated table. so instead of a materialised view we will go with a table and use triggers to do **atomic updates**

Tried option 1 - it is functionally equivalent to the current state of affairs, so there's no reason to expect that performance will improve as a result.

Going ahead with option 2:
* using aggregate tables instead of views
* use triggers to do atomic updates on individual rows whenever we use  insert/update operations in our worker code

**Comment by ramyaragupathy** [comment]
In short this means:
triggers :white_check_mark:
materialized views :x: 
tables: :white_check_mark:
