### ISSUE TITLE
need badges for "Roles" courses

### ISSUE THREAD

**Issue by mikelmaron** [hotosm/tech#80]

**Comment by russdeffner** [comment]
I think this can be closed, as all Activation courses have the badging stuff done.

**Comment by mikelmaron** [comment]
where can we see the badges?

**Comment by russdeffner** [comment]
The essentials course has one badge, all other role courses have two - I think you just click 'badges' under each course title.

**Comment by russdeffner** [comment]
This has been complete for several years now.
