### ISSUE TITLE
move courses.hotosm.org to GitBooks

### ISSUE THREAD

**Issue by mikelmaron** [hotosm/tech#89]
@bgirardot @russdeffner and I got a start on this here https://www.gitbook.com/book/bgirardot/hotosm-activation-curriculum/details. Would be good to find a time for Activation WG to power through and complete the move, then look at iterative improvements.

**Comment by russdeffner** [comment]
The link has been copied to #83 - we can close this issue now.

**Comment by smit1678** [comment]
👍 closing to track the convo in #83 then.
