### ISSUE TITLE
Proposal to change repo name

### ISSUE THREAD

**Issue by smit1678** [hotosm/tech#92]
While this repo has traditionally been not very active, we're going to work to use this space more for coordinating and discussing tech related projects within HOT. As a part of the effort to leverage Github more for coordinating and documenting tech project discussions, I'm proposing we change this repo to `tech`; this replaces the current name `hotosm-system-admin`. 

The thinking here is that this will help simplify the name and help this repo become a central point for tech discussions. Individual project repos will still house specific code and implementation discussions. 

cc @mataharimhairi

**Comment by mataharimhairi** [comment]
I agree, that it should be a repo for more general discussion surrounding all technical projects and the supporting infrastructure, including sys admin items.

Can I please suggest `hot-tech`, since it is a little more specific as to which tech we are referring to ;) @smit1678

**Comment by smit1678** [comment]
> Can I please suggest hot-tech, since it is a little more specific as to which tech we are referring to ;) 

Definitely open to it. My leaning towards just `tech` is because the full Github url would then be `https://github.com/hotosm/tech`. otherwise it's `https://github.com/hotosm/hot-tech`. It is a minor detail so I'm open either way.

**Comment by smit1678** [comment]
If no other discussion, closing this.
