### ISSUE TITLE
Tech Working Group meeting times, include a new time for Asia

### ISSUE THREAD

**Issue by smit1678** [hotosm/tech#93]
From discussion between myself, @mataharimhairi, and others, there is some interest in having a more optimal time for those in Asia. The thinking here is that perhaps we could have two sets of tech working group meetings to coordinate or make sure there is an opportunity for everyone to discuss in real time (not just async). This will raise the need to capture notes in both sessions but I think ultimately give people a chance to participate in discussions. Note that you wouldn't need to attend both (we'll capture notes to make sure things discussed in Asia are factored into the discussion later in the day). 

## Proposed times: 
Both meetings are being proposed for the same day, 2nd and 4th Tuesday of every month. This is different from what we've been doing, weekly. Having this bi-weekly may be helpful for people to attend. 

1. Asia - 08:00 UTC 
2. Europe/Americas - 15:00 UTC 

## Location: 

Is it worth doing one of these meetings via Mumble or another voice chat like Hangout or Zoom? Maybe it's helpful to have the first meeting is done via voice (2nd Tuesday), and then second meeting is done via chat. 

Open to further discussion if there is objections.

**Comment by ethan-nelson** [comment]
I guess I'll chime in to get the convo going. Twice monthly meetings and the dual times both seem like good ideas! The voice meeting would be okay--I'm not always in a position to be able to talk during a meeting, but as long as one of these mediums (or another that also supports text chat) is used, then that could work.

**Comment by mataharimhairi** [comment]
Agreed. Meetings twice a month, with the first being via voice chat and the second through text chat, would be a great start.

I am also happy to lead the allocated time for Asia at 08:00 UTC. It would be great to build up more of a Tech WG community here to get their invaluable input!

**Comment by smit1678** [comment]
> The voice meeting would be okay--I'm not always in a position to be able to talk during a meeting, but as long as one of these mediums (or another that also supports text chat) is used, then that could work.

@ethan-nelson yeah I totally understand that. We should make sure we use a medium that allows both types of access.  

> I am also happy to lead the allocated time for Asia at 08:00 UTC. It would be great to build up more of a Tech WG community here to get their invaluable input!

Thanks @mataharimhairi

**Comment by smit1678** [comment]
This seemed to have worked well for our [first meeting on December 12](https://github.com/hotosm/tech/wiki/Meetings).
